# Generated by Django 3.1.3 on 2020-11-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
