# Generated by Django 3.1.3 on 2020-11-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
