# Generated by Django 3.1.3 on 2020-11-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='jointed_users',
            field=models.ManyToManyField(related_name='joined_trips', to='app_one.User'),
        ),
    ]
